### ISSUE TITLE
CONTROLS-nmpc-demo

### ISSUE THREAD

**Issue by gracetangg** [carnegie-autonomous-racing/cmr-fsdv#10]
## Task Description:
...

## Task Check-list:
- [ ] ...
- [ ] Write integration tests
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] Update [Smartsheet](https://app.smartsheet.com/sheets/phJjhWq5VvpqHHw8WW5rCRh8Xgccpv8Q96WCMr41?view=grid) with Task Timeline

Comment any questions and tag reviewers.

**Comment by cmrat** [comment]
This branch is solely for demonstration purposes so no development should happen on it.
