### ISSUE TITLE
CONTROLS-rewrite-demo-script

### ISSUE THREAD

**Issue by cmrat** [carnegie-autonomous-racing/cmr-fsdv#11]
## Task Description:
Rewrite the demo script based on the newest model and controller

## Task Check-list:
- [ ] Rewrite Demo Script
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] Update [Smartsheet](https://app.smartsheet.com/sheets/phJjhWq5VvpqHHw8WW5rCRh8Xgccpv8Q96WCMr41?view=grid) with Task Timeline

Comment any questions and tag reviewers.
