### ISSUE TITLE
PERCEPTIONS-optimize-plane-fitting

### ISSUE THREAD

**Issue by dinodeep** [carnegie-autonomous-racing/cmr-fsdv#15]
## Task Description:
Optimize the plane fitting filtering algorithm in filter.py to improve timing performance. Currently, operates at 3-4ms for a point cloud of ~6K points, but aiming for 2-3x speedup, so try to reach 1-2ms.

## Task Check-list:
- [ ] Optimized plane fitting algorithm averages for 1-2ms time for the sim-images dataset
- [ ] Optimized plane fitting algorithm operates produces the same result as the original plane fitting algorithm
- [ ] Open Pull Request

## Task Timeline:
- [ ] Update [Smartsheet](https://app.smartsheet.com/sheets/phJjhWq5VvpqHHw8WW5rCRh8Xgccpv8Q96WCMr41?view=grid) with Task Timeline
