### ISSUE TITLE
PERCEPTIONS-optimize-dataset-generation

### ISSUE THREAD

**Issue by dinodeep** [carnegie-autonomous-racing/cmr-fsdv#17]
## Task Description:
We currently have a script for generating simulated LiDAR point clouds with random cones placed in an empty space. Currently, it takes approximately ~6s to generate a single point cloud on the settings listed in the command below.
`python3 generate.py -N 1 -C 10 -M 20 -H 2 -R 0.1 -L 20`

This process can be improved whether via multiprocessing or vectorization using NumPy to improve the performance of generating a single point cloud. Using these same settings, try to achieve 15x speedup. 

## Task Check-list:
- [ ] Code is optimized to run at most 0.5s per point cloud on the command `python3 generate.py -N 1 -C 10 -M 20 -H 2 -R 0.1 -L 20`
- [ ] Code produces point clouds that are accurately randomly generated and well-represent what was produced by the original script
- [ ] Vectorized/optimized functions that are deterministic should produce exactly the same results as their slow counterparts
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] Update [Smartsheet](https://app.smartsheet.com/sheets/phJjhWq5VvpqHHw8WW5rCRh8Xgccpv8Q96WCMr41?view=grid) with Task Timeline

Comment any questions and tag reviewers.
