### ISSUE TITLE
Path Finding - Frenet Serret

### ISSUE THREAD

**Issue by ishinshah** [carnegie-autonomous-racing/cmr-fsdv#18]
## Task Description: Frenet Serret Frame
Parameterize Path, find progress at the current point, find curvature and its derivative at the point

## Task Check-list:
- [ ] Create Curvature code
- [ ] Find derivative or curvature
- [ ] Test to make sure progress is accurate
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] Update [Smartsheet](https://app.smartsheet.com/sheets/phJjhWq5VvpqHHw8WW5rCRh8Xgccpv8Q96WCMr41?view=grid) with Task Timeline

Comment any questions and tag reviewers.
