### ISSUE TITLE
SOFTWARE-slam-integration

### ISSUE THREAD

**Issue by gracetangg** [carnegie-autonomous-racing/cmr-fsdv#2]
## Task Description:
Integrate Path Planning SLAM software within a PathPlanningTask. If necessary, speak to Path Planning members to edit methods to take in input data (list of (x, y, z) coordinates from perceptions) and map out the output data type for controls. Determine which methods are needed to run one iteration of the SLAM pipeline (disregard the midpoint spline pipeline). 

Create a separate driver and gather test data from path planning. Run a few profiling techniques (cProfile, etc.) to profile the time and memory usage of the pipeline. Recommend going through a few different methodologies for each time and memory because different techniques run with different assumptions. Report profiling data in a Google Sheet and post a link in the comment. 

A few profiling resources: 
* https://towardsdatascience.com/how-to-profile-your-code-in-python-e70c834fad89
* https://machinelearningmastery.com/profiling-python-code/
* https://www.infoworld.com/article/3600993/9-fine-libraries-for-profiling-python-code.html

## Task Check-list:
- [ ] Read through and understand [slam](https://github.com/carnegie-autonomous-racing/Path-Planning/tree/integration/EFK%20SLAM) pipeline
- [ ] If changes to certain methods need to be made (to accommodate for passing in data rather than encapsulation) do so in partnership with path planning team members (ask questions if need a point of contact)
- [ ] Integrate into the [`PathPlanningTask` Object](https://github.com/carnegie-autonomous-racing/software-architecture/blob/main/carcode/control/pathplanning.py)
- [ ] Test data transference with testing data and mock driver
- [ ] Log flags as they may occur, incorrect data input/output, etc. 
- [ ] Profile with different methods and report memory/time consumption per one iteration of the (SLAM) code, again disregard the midpoint spline pipeline for now.
- [ ] Document points of memory/time bottle necks + Google Sheets below
- [ ] Integration tests (if set up in time)
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] October 14th: everything should be integrated, tested, profiled
- [ ] Update [Smartsheet](https://app.smartsheet.com/sheets/phJjhWq5VvpqHHw8WW5rCRh8Xgccpv8Q96WCMr41?view=grid) with Task Timeline 

Comment any questions and tag reviewers.
