### ISSUE TITLE
CONTROLS-redesign-mochi-cost-function

### ISSUE THREAD

**Issue by cmrat** [carnegie-autonomous-racing/cmr-fsdv#20]
## Task Description:
Redesign the cost function of MOCHI and implement state dimensionality minimization

## Task Check-list:
- [ ] Redesign cost function
- [ ] Minimize state dimension
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] Update [Smartsheet](https://app.smartsheet.com/sheets/phJjhWq5VvpqHHw8WW5rCRh8Xgccpv8Q96WCMr41?view=grid) with Task Timeline

Comment any questions and tag reviewers.
