### ISSUE TITLE
CONTROLS-improve-simulation-interface

### ISSUE THREAD

**Issue by cmrat** [carnegie-autonomous-racing/cmr-fsdv#22]
## Task Description:
The Simulink wrapper of the symbolic dynamics models is very primitive right now. We should improve its usability by properly designing a simulation interface that is usable by Controls, Path Planning, and Vehicle Dynamics.

## Task Check-list:
- [ ] Define the intended use case
- [ ] Design a easy-to-use simulation interface
- [ ] Improve visualization
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] Update [Smartsheet](https://app.smartsheet.com/sheets/phJjhWq5VvpqHHw8WW5rCRh8Xgccpv8Q96WCMr41?view=grid) with Task Timeline

Comment any questions and tag reviewers.
