### ISSUE TITLE
CONTROLS-ahrs-driver

### ISSUE THREAD

**Issue by cmrat** [carnegie-autonomous-racing/cmr-fsdv#23]
## Task Description:
Develop and validate the driver for the AHRS.

## Task Check-list:
- [ ] Write the communication protocol state machine
- [ ] Write the packet decoder
- [ ] Write the UART driver
- [ ] Validate on the Jetson
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] Update [Smartsheet](https://app.smartsheet.com/sheets/phJjhWq5VvpqHHw8WW5rCRh8Xgccpv8Q96WCMr41?view=grid) with Task Timeline

Comment any questions and tag reviewers.
