### ISSUE TITLE
SOFTWARE-midpointspline-integration

### ISSUE THREAD

**Issue by gracetangg** [carnegie-autonomous-racing/cmr-fsdv#3]
## Task Description:
Integrate Path Planning Midpoint Spline software within the [`PathPlanningTask`](https://github.com/carnegie-autonomous-racing/software-architecture/blob/main/carcode/control/pathplanning.py). If necessary, speak to Path Planning members to edit methods to take in input data (list of (x, y, z) coordinates from perceptions) and map out the output data type for controls. Determine which methods are needed to run one iteration of the Midpoint spline pipeline (disregard the SLAM pipeline). 

**Path Planning has two different pipelines (for the first lap vs. for every other lap)** as we discuss with other team members how to determine when we move from the midpoint spline pipeline to the SLAM pipeline, please just keep software under a simple temorary if statement (i.e. `if isFirstLap():`). 

Create a separate driver and gather test data from path planning. Run a few profiling techniques (cProfile, etc.) to profile the time and memory usage of the pipeline. Recommend going through a few different methodologies for each time and memory because different techniques run with different assumptions. Report profiling data in a Google Sheet and post a link in the comment. 

A few profiling resources: 
* https://towardsdatascience.com/how-to-profile-your-code-in-python-e70c834fad89
* https://machinelearningmastery.com/profiling-python-code/
* https://www.infoworld.com/article/3600993/9-fine-libraries-for-profiling-python-code.html

## Task Check-list:
- [ ] Read through and understand [midpoint spline](https://github.com/carnegie-autonomous-racing/software-architecture/blob/main/carcode/control/pathplanning.py) pipeline
- [ ] Take the code found in the current [`PathPlanningTask`](https://github.com/carnegie-autonomous-racing/software-architecture/blob/main/carcode/control/pathplanning.py) and move it into another file under `pathplanning/` directory. Make sure the pipeline we call (and any functions) directly take in data and no data is encapsulated within another object.
- [ ] If changes to certain methods need to be made (to accommodate for passing in data) do so in partnership with path planning team members (ask questions if need a point of contact)
- [ ] Integrate into the [`PathPlanningTask`](https://github.com/carnegie-autonomous-racing/software-architecture/blob/main/carcode/control/pathplanning.py)
- [ ] Test data transference with testing data and mock driver
- [ ] Log flags as they may occur, incorrect data input/output, etc. 
- [ ] Profile with different methods and report memory/time consumption per one iteration of the (midpoint spline) code, again disregard the SLAM pipeline for now.
- [ ] Document points of memory/time bottle necks + Google Sheets below
- [ ] Integration tests (if set up in time)
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] October 14th: everything should be integrated, tested, profiled
- [ ] Update [Smartsheet](https://app.smartsheet.com/sheets/phJjhWq5VvpqHHw8WW5rCRh8Xgccpv8Q96WCMr41?view=grid) with Task Timeline 

Comment any questions and tag reviewers.
