### ISSUE TITLE
SOFTWARE-lqr-integration

### ISSUE THREAD

**Issue by gracetangg** [carnegie-autonomous-racing/cmr-fsdv#4]
## Task Description:
Integrate Controls LQR Controller software within the ControlsTask. If necessary, speak to controls members (@yuvanshu) to edit methods to take in input data (from path planning) and output acceleration, steering angle, velocity, etc. Determine which methods are needed to run one iteration of the pipeline. 

Create a separate driver and gather test data from controls. Run a few profiling techniques (cProfile, etc.) to profile the time and memory usage of the pipeline. Recommend going through a few different methodologies for each time and memory because different techniques run with different assumptions. Report profiling data in a Google Sheet and post a link in the comment. 

A few profiling resources: 
* https://towardsdatascience.com/how-to-profile-your-code-in-python-e70c834fad89
* https://machinelearningmastery.com/profiling-python-code/
* https://www.infoworld.com/article/3600993/9-fine-libraries-for-profiling-python-code.html

## Task Check-list:
- [ ] Read through and understand [lqr](https://github.com/carnegie-autonomous-racing/software-architecture/blob/controls_lqr/carcode/control/controls_lqr.py) pipeline, ask @yuvanshu for clarifications
- [ ] Take the code found in the current [`ControlsLQR`](https://github.com/carnegie-autonomous-racing/software-architecture/blob/controls_lqr/carcode/control/controls_lqr.py) and move it into another file under `controls/` directory. Make sure the pipeline we call (and any functions) directly takes in data and no data is encapsulated within another object.
- [ ] If changes to certain methods need to be made (to accommodate for passing in data) do so in partnership with controls team members (ask question if need a point of contact)
- [ ] Integrate into a `ControlsTask` Object
- [ ] Test data transference with testing data and mock driver
- [ ] Log flags as they may occur, incorrect data input/output, etc. 
- [ ] Profile with different methods and report memory/time consumption per one iteration of the code
- [ ] Document points of memory/time bottle necks + Google Sheets below
- [ ] Integration tests (if set up in time)
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] October 14th: everything should be integrated, tested, profiled
- [ ] Update [Smartsheet](https://app.smartsheet.com/sheets/phJjhWq5VvpqHHw8WW5rCRh8Xgccpv8Q96WCMr41?view=grid) with Task Timeline 

Comment any questions and tag reviewers.

**Comment by cmrat** [comment]
Personally, I think we should choose one between PID and LQR to deploy on the 1/5th scale vehicle. Both controllers have simple structures. PID is model-free, thus easier to understand and tune. LQR would handle MIMO better, but requires a adequately correct linearized model. I'll leave the decision to @yuvanshu and @gracetangg.
