### ISSUE TITLE
SOFTWARE-integration-testing

### ISSUE THREAD

**Issue by gracetangg** [carnegie-autonomous-racing/cmr-fsdv#5]
## Task Description:
R&D for proper integration testing techniques for our current vehicle software. There is currently testing software in place, but we want to expand on this, as well as set up automated integration testing with software such as TravisCI, GitHub Actions. 

Create a Proposal for how to enforce testing among the subteams and for deployment code (specifically software). Present a proposal in a PDR during a software meeting for feedback. Then begin implementation
 
## Task Check-list:
- [ ] Research conventional testing methods for Python packages, specifically robotics software. Document in [Confluence](http://cmr.red/confluence/display/AUTO/Research+Notes) under Research Notes, create a new page. 
- [ ] Determine which automated integration method is best for our team/needs. May propose multiple for the team to discuss as well (or do brief overviews and proposals during weekly updates).
- [ ] Give proposal (PDR) for: implementation structure for different forms of development, which automation service we will use, etc. 
- [ ] Review PDR notes and make corresponding corrections
- [ ] Begin implementing
- [ ] Give CDR/presentation during all-hands
- [ ] Write integration tests lol
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] October 14th: integration testing PDR given, approved, implemented. Maybe CDR given before Fall Break, if not after. 
- [ ] Update [Smartsheet](https://app.smartsheet.com/sheets/phJjhWq5VvpqHHw8WW5rCRh8Xgccpv8Q96WCMr41?view=grid) with Task Timeline

Comment any questions and tag reviewers.
