### ISSUE TITLE
SOFTWARE-ros2-ros2-structure-setup

### ISSUE THREAD

**Issue by gracetangg** [carnegie-autonomous-racing/cmr-fsdv#7]
## Task Description:
From ros2 task introduction (#6): 
1. Understand ROS and its overall structure
2. Understand best practices for designing, building, documenting ROS packages
3. Understand best practices for designing ROS nodes, topics, and launch files
4. Create a data dependency map for nodes and topics
5. Present PDR during Software meeting before implementation
6. Implement reviews from PDR before presenting CDR at all-hands

## Task Check-list:
- [ ] Research ROS2 package, node, topic, launch file design. Document in [Confluence](http://cmr.red/confluence/display/AUTO/Research+Notes) under Research Notes, create a new page. 
- [ ] Create data dependency map of nodes to topics
- [ ] Design structure for each node/topic (aka topic message types, defining those as necessary) and implementing shell for all subteam code to be placed 
- [ ] Give proposal (PDR) for: implementation structure for different forms of development, which automation service we will use, etc. 
- [ ] Review PDR notes and make corresponding corrections
- [ ] Give CDR/presentation during all-hands
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] Oct 14: Nodes, topics, launch files setup, ready for subteam integration
- [ ] Update [Smartsheet](https://app.smartsheet.com/sheets/phJjhWq5VvpqHHw8WW5rCRh8Xgccpv8Q96WCMr41?view=grid) with Task Timeline

Comment any questions and tag reviewers.
