### ISSUE TITLE
SOFTWARE-ros2-testing-setup

### ISSUE THREAD

**Issue by gracetangg** [carnegie-autonomous-racing/cmr-fsdv#8]
## Task Description:
1. Understand ROS and its overall structure
2. Research best practices for testing nodes/modules within a ROS package. 
3. Present PDR during Software meeting before implementation. 

*Comment all resources found in comments below as well as in Confluence*

## Task Check-list:
- [ ] Research into ROS2 testing practices. Document in [Confluence](http://cmr.red/confluence/display/AUTO/Research+Notes) under Research Notes, create a new page. 
- [ ] Determine which automated integration method is best for our team/needs. May propose multiple for the team to discuss as well (or do brief overviews and proposals during weekly updates).
- [ ] Give proposal (PDR) for: implementation structure for different forms of development, which automation service we will use, etc. 
- [ ] Review PDR notes and make corresponding corrections
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] Oct 23: ROS testing environment set up
- [ ] Update [Smartsheet](https://app.smartsheet.com/sheets/phJjhWq5VvpqHHw8WW5rCRh8Xgccpv8Q96WCMr41?view=grid) with Task Timeline

Comment any questions and tag reviewers.
