### ISSUE TITLE
SOFTWARE-simulation

### ISSUE THREAD

**Issue by gracetangg** [carnegie-autonomous-racing/cmr-fsdv#9]
## Task Description:
Determine the end-to-end topics that must be examined for subteams: 
* Currently Perceptions needs the LiDar Pointclouds (later on stereo camera frames)
* Publish to `cmd/` topic for controlling the car
* Aid in simulation testing: passing data through the pipeline and profiling to determine inaccuracies with vehicle software

## Task Check-list:
- [ ] Test subscribing to the Lidar Pointcloud topic. Subscriber classes are defined [here](https://github.com/carnegie-autonomous-racing/software-architecture/blob/controls_lqr/carcode/actuate/simulator.py)
- [ ] Determine message type of topic and how to convert into the image/point cloud format expected from perceptions
- [ ] Determine message type of topic for `cmd/` and how to convert the outputs from controls into expected format
- [ ] Test publishing and subscribing to ensure simulation validity
- [ ] Aid in Simulation Testing (start before Fall Break)
- [ ] Write integration tests
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] Oct 14: Done with end-to-end testing, begin full vehicle testing
- [ ] Update [Smartsheet](https://app.smartsheet.com/sheets/phJjhWq5VvpqHHw8WW5rCRh8Xgccpv8Q96WCMr41?view=grid) with Task Timeline

Comment any questions and tag reviewers.
